# --- RESNET50 --- #
resnet50: &resnet50
  model: resnet50
  data: imagenet
  precision: "16.16"
  enable_stochastic_rounding: true
  label_smoothing: 0.1
  weight_decay: 0.0001
  optimizer: sgd_combined
  lr: 0.5
  lr_schedule: cosine
  momentum: 0.85
  warmup_epoch: 5
  epoch: 100
  norm_type: group
  norm_num_groups: 32
  loss_scaling: 128
  lr_scheduler_freq: 16
  half_partial: true
  device_iterations: 1
  loss_velocity_scaling_ratio: 1
  seed: 42


resnet50_mk2: &resnet50_mk2
  <<: *resnet50
  precision: "16.16"
  momentum: 0.9
  lr: 2.0
  batch_size: 18
  pipeline_splits: []
  replicas: 16
  gradient_accumulation: 57
  device_iterations: 1
  norm_type: batch
  offload_optimizer: false
  half_partial: true
  eight_bit_io: true
  normalization_location: ipu
  use_bbox_info: true
  exchange_memory_target: memory
  recompute_mode: manual
  recompute_checkpoints: [add, add/1, add/2, add/3, add/5, add/6, add/7, add/9, add/11, add/12]
  disable_stable_batchnorm: true
  available_memory_proportion: [0.12]


resnet50_mk2_pod64:
  <<: *resnet50_mk2
  replicas: 64
  gradient_accumulation: 14


# --- EfficientNet --- #
efficientnet-g16-gn-16ipu-mk2-base: &efficientnet-g16-gn-16ipu-mk2-base
  data: imagenet
  seed: 0
  precision: "16.32"
  eight_bit_io: true
  normalization_location: ipu
  use_bbox_info: true
  enable_stochastic_rounding: false
  efficientnet_group_dim: 16
  efficientnet_expand_ratio: 4
  norm_type: group
  norm_eps: 0.001
  norm_num_groups: 4
  epoch: 350
  warmup_epoch: 5
  optimizer: rmsprop_tf
  optimizer_eps: 0.001
  momentum: 0.9
  rmsprop_decay: 0.953125
  offload_optimizer: false
  lr_schedule: exponential
  lr_scheduler_freq: 0.424
  lr_decay: 0.97
  loss_scaling: 128
  weight_decay: 0.00001
  label_smoothing: 0.1
  weight_avg_strategy: exponential
  weight_avg_exp_decay: 0.97
  available_memory_proportion: [0.15]
  exchange_memory_target: balanced
  half_partial: true
  enable_fast_groupnorm: true


efficientnet-b0-g16-gn-16ipu-mk2:
  <<: *efficientnet-g16-gn-16ipu-mk2-base
  model: efficientnet-b0
  pipeline_splits: [blocks/3/0]
  lr: 0.05
  batch_size: 20
  replicas: 8
  gradient_accumulation: 5
  mixup_alpha: 0.1


efficientnet-b4-g16-gn-16ipu-mk2:
  <<: *efficientnet-g16-gn-16ipu-mk2-base
  model: efficientnet-b4
  pipeline_splits: [blocks/1/1, blocks/3/0, blocks/4/5]
  lr: 0.0483
  batch_size: 6
  replicas: 4
  gradient_accumulation: 32
  device_iterations: 4
  mixup_alpha: 0.2
  cutmix_lambda_low: 0.65
  cutmix_lambda_high: 1.0
  cutmix_disable_prob: 0.35


# --- MobileNet v3--- #
mobilenet-v3-base: &mobilenet-v3-base
  data: imagenet
  label_smoothing: 0.1
  weight_decay: 0.00003
  optimizer: sgd_combined
  lr_schedule: cosine
  warmup_epoch: 5
  initial_loss_scaling: 128
  loss_scaling: 128
  seed: 42
  norm_type: batch
  offload_optimizer: false
  half_partial: true
  eight_bit_io: true
  normalization_location: ipu
  epoch: 360
  momentum: 0.9
  lr: 0.52
  device_iterations: 1
  validation_mode: after
  batch_size: 32


mobilenet-v3-small: &mobilenet-v3-small
  <<: *mobilenet-v3-base
  model: mobilenet-v3-small
  precision: "16.16"
  recompute_mode: auto
  gradient_accumulation: 32
  replicas: 1
  enable_stochastic_rounding: true


mobilenet-v3-small-pod4:
  <<: *mobilenet-v3-small
  replicas: 4
  gradient_accumulation: 8
  enable_stochastic_rounding: false


mobilenet-v3-large: &mobilenet-v3-large
  <<: *mobilenet-v3-base
  model: mobilenet-v3-large
  precision: "16.32"
  pipeline_splits: [mb_block/2, mb_block/7, mb_block/11] #16.32
  gradient_accumulation: 32
  replicas: 1
  enable_stochastic_rounding: true


mobilenet-v3-large-pod16:
  <<: *mobilenet-v3-large
  replicas: 4
  gradient_accumulation: 8
  enable_stochastic_rounding: false


timm_resnetv2_50d_gn: &timm_resnetv2_50d_gn
  <<: *resnet50
  model: timm.resnetv2_50d_gn
  precision: "16.16"
  momentum: 0.9
  lr: 2.0
  lr_schedule: cosine
  batch_size: 16
  label_smoothing: 0.1
  drop_rate: 0.1
  drop_path_rate: 0.05
  weight_decay: 0.00002
  optimizer: sgd_combined
  warmup_epoch: 5
  epoch: 400
  pipeline_splits: []
  replicas: 16
  gradient_accumulation: 50
  device_iterations: 1
  offload_optimizer: false
  half_partial: true
  eight_bit_io: true
  normalization_location: ipu
  use_bbox_info: true
  exchange_memory_target: memory
  recompute_mode: manual
  recompute_checkpoints: [add, add/1, add/2, add/3, add/5, add/6, add/7, add/9, add/11, add/12]
  disable_stable_batchnorm: true
  available_memory_proportion: [0.12]


timm_resnetv2_50d_gn_lamb: &timm_resnetv2_50d_gn_lamb
  <<: *timm_resnetv2_50d_gn
  model: timm.timm_resnetv2_50d_gn
  precision: "16.16"
  lr: .002
  weight_decay: 0.02
  optimizer: lamb


timm_resnetv2_50d_evos0: &timm_resnetv2_50d_evos0
  <<: *resnet50
  model: timm.resnetv2_50d_evos0
  precision: "16.16"
  momentum: 0.9
  lr: 2.0
  lr_schedule: cosine
  batch_size: 16
  label_smoothing: 0.1
  drop_rate: 0.1
  drop_path_rate: 0.05
  weight_decay: 0.00002
  optimizer: sgd_combined
  warmup_epoch: 5
  epoch: 400
  pipeline_splits: []
  replicas: 16
  gradient_accumulation: 57
  device_iterations: 1
  offload_optimizer: false
  half_partial: true
  eight_bit_io: true
  normalization_location: ipu
  use_bbox_info: true
  exchange_memory_target: memory
  recompute_mode: manual
  recompute_checkpoints: [add, add/1, add/2, add/3, add/5, add/6, add/7, add/9, add/11, add/12]
  disable_stable_batchnorm: true
  available_memory_proportion: [0.12]


